name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: GitHub Pages  # Reference your environment here

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2  # Use the latest stable version

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        jsApiKey: ${{ secrets.apiKey }}  # Your secret reference

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
